
<h1><left>Introduction to Python</left></h1>

By: Ana-Maria O'Brien <br>
Date: 25rd June 2020
<!--eofm-->


<h1><center>Chapter 1: Python Basics</center></h1>



# Python as a Calculator

Python is perfectly suited to do basic calculations. Apart from addition, subtraction, multiplication and division, there is also support for more advanced operations such as:

* Exponentiation: ** . This operator raises the number to its left to the power of the number to its right. 
For example 4 ** 2 will give 16.
* Modulo: %. This operator returns the remainder of the division of the number to the left by the number on its right. For example 18 % 7 equals 4.


In [1]:
# Addition
5+5

10

In [2]:
# Subtraction
5-5

0

In [3]:
# Multiplication
3 * 5

15

In [4]:
# Division
10 / 2

5.0

In [5]:
# Modulo
18 % 7

4

In [6]:
# Exponentiation
4 ** 2

16

In [7]:
# Suppose you have $100, which you can invest with a 10% return each year. After one year, it's 100 × 1.1 = 110 dollars, 
# and after two years it's 100 × 1.1 × 1.1 = 121

# How much is your $100 worth after 7 years?

100*1.1**7

194.87171000000012

# Variables and Types

Important to note:

Different types of data behave differently. For example 2 + 3 = 5 but 'ab' + 'cd = 'abcd.




To conclude **'Different type = different behaviour'**


Different types of variables are as follows:


* **int**, or integer: a number without a fractional part. savings, with the value 100, is an example of an integer.
* **float**, or floating point: a number that has both an integer and fractional part, separated by a point. growth_multiplier, with the value 1.1, is an example of a float.

Next to numerical data types, there are two other very common data types:

* **str**, or string: a type to represent text. You can use single or double quotes to build a string.
* **bool**, or boolean: a type to represent logical values. Can only be **True** or **False** (the capitalization is important!).


# Variable Assignment

In Python, a variable allows you to refer to a value with a name. To create a variable use =, like this example:

x = 5
You can now use the name of this variable, x, instead of the actual value, 5.

Remember, = in Python means assignment, it doesn't test equality!

In [8]:
# Create a variable savings
savings = 100

# Print out savings
savings

100

In [9]:
# Create a variable growth_multiplier, equal to 1.1
growth_multiplier = 1.1

# Create a variable factor
factor = 1.10


# Create a variable, result, equal to the amount of money you saved after 7 years.
result = savings*factor ** 7

# Calculate result
result 

194.87171000000012

In [10]:
# Create a new string, desc, with the value "compound interest"

desc = "compound interest"

# Create a new boolean, profitable, with the value True

profitable = True

# Guess the type

To find out the type of a value or a variable that refers to that value, you can use the **type()** function. Suppose you've defined a variable a, but you forgot the type of this variable. To determine the type of a, simply execute:

type(a)


In [11]:
# Assign product of growth_multiplier and savings to year1
year1 = growth_multiplier*savings
# Print the type of year1
type(year1)

# Assign sum of desc and desc to doubledesc
doubledesc = desc + desc

# Print out doubledesc
doubledesc

'compound interestcompound interest'

# Type conversion

Using the + operator to paste together two strings can be very useful in building custom messages.

Suppose, for example, that you've calculated the return of your investment and want to summarize the results in a string. Assuming the integer savings and float result are defined, you can try something like this:

print("I started with $" + savings + "  and  now  have $" + result + ". Awesome!")


In [12]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7



# Using print statement to print the following
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)

I started with $100 and now have $194.87171000000012. Awesome!


<h1><center>Chapter 2: Python Lists</center></h1>

# Create a list

As opposed to int, bool etc., a list is a compound data type; you can group values together:

a = "is" <br>
b = "nice" <br>
my_list = ["my", "list", a, b] <br>

After measuring the height of your family, you decide to collect some information on the house you're living in. The areas of the different parts of your house are stored in separate variables for now, as shown in the script.

In [13]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas=[hall,kit,liv,bed,bath]

# Print areas use print(areas) in spyder script but not essential in notebook
areas

[11.25, 18.0, 20.0, 10.75, 9.5]

In [14]:
# Adapt list areas
areas = ["hallway", 11.25, "kitchen",18.0, "living room",20.0, "bedroom",10.75, "bathroom",9.50]

# This list contains both strings and floats, but that's not a problem for Python!
areas

['hallway',
 11.25,
 'kitchen',
 18.0,
 'living room',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 9.5]

In [15]:
# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]
# Print out house
house


[['hallway', 11.25],
 ['kitchen', 18.0],
 ['living room', 20.0],
 ['bedroom', 10.75],
 ['bathroom', 9.5]]

In [16]:
# Print out the type of house
type(house)

list

# Subset and conquer

Subsetting Python lists is a piece of cake. Take the code sample below, which creates a list x and then selects "b" from it. Remember that this is the second element, so it has index 1. You can also use negative indexing.

x = ["a", "b", "c", "d"] <br>
x[1] <br>
x[-3] # same result! <br>

In [17]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


# Subset and calculate

After you've extracted values from a list, you can use them to perform additional calculations. Take this example, where the second and fourth element of a list x are extracted. The strings that result are pasted together using the + operator:

x = ["a", "b", "c", "d"] <br>
print(x[1] + x[3])

In [18]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[-3]
# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


# Slicing and dicing

Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax:

my_list[start:end] <br>

**The start index will be included, while the end index is not.**

The code sample below shows an example. A list with "b" and "c", corresponding to indexes 1 and 2, are selected from a list x:

x = ["a", "b", "c", "d"] <br>
x[1:3] <br>
The elements with index 1 and 2 are included, while the element with index 3 is not.

In [19]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs

upstairs = areas [6:10]
# Print out downstairs and upstairs

print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


# Slicing and dicing (2)

In the video, Hugo first discussed the syntax where you specify both where to begin and end the slice of your list:

my_list[begin:end] <br> 

However, it's also possible not to specify these indexes. If you don't specify the begin index, Python figures out that you want to start your slice at the beginning of your list. If you don't specify the end index, the slice will go all the way to the last element of your list. To experiment with this, try the following commands in the IPython Shell:

x = ["a", "b", "c", "d"] <br>
x[:2] <br>
x[2:] <br>
x[:]

In [20]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs
downstairs = areas[:6]

# Alternative slicing to create upstairs
upstairs = areas[-4:]

# Replace list elements

Replacing list elements is pretty easy. Simply subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once.

Use the IPython Shell to experiment with the commands below. Can you tell what's happening and why?

x = ["a", "b", "c", "d"] <br>
x[1] = "r" <br>
x[2:] = ["s", "t"]


As the code sample showed, you can also slice a list and replace it with another list to update multiple elements in a single command.

In [21]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

# Extend a list

If you can change elements in a list, you sure want to be able to add elements to it, right? You can use the + operator:

x = ["a", "b", "c", "d"] <br>
y = x + ["e", "f"]

In [22]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1

areas_1 = areas + ["poolhouse", 24.5]
# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

# Delete list elements

Finally, you can also remove elements from your list. You can do this with the del statement:

x = ["a", "b", "c", "d"]
del(x[1])
Pay attention here: as soon as you remove an element from a list, the indexes of the elements that come after the deleted element all change!

The updated and extended version of areas that you've built in the previous exercises is coded below. You can copy and paste this into the IPython Shell to play around with the result. <br>

areas = ["hallway", 11.25, "kitchen", 18.0, <br>
        "chill zone", 20.0, "bedroom", 10.75, <br>
         "bathroom", 10.50, "poolhouse", 24.5, <br>
         "garage", 15.45]


There was a mistake! The amount you won with the lottery is not that big after all and it looks like the poolhouse isn't going to happen. You decide to remove the corresponding string and float from the areas list.

The ; sign is used to place commands on the same line. The following two code chunks are equivalent:

#Same line <br>
command1; command2

#Separate lines <br>
command1 <br>
command2 <br>


Which of the code chunks will do the job for us? <br>
del(areas[-4:-2])


# Inner workings of lists

At the end of the video, Hugo explained how Python lists work behind the scenes. In this exercise you'll get some hands-on experience with this.

The Python code in the script already creates a list with the name areas and a copy named areas_copy. Next, the first element in the areas_copy list is changed and the areas list is printed out. If you hit Run Code you'll see that, although you've changed areas_copy, the change also takes effect in the areas list. That's because areas and areas_copy point to the same list.

If you want to prevent changes in areas_copy from also taking effect in areas, you'll have to do a more explicit copy of the areas list. You can do this with list() or by using [:].

In [23]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

# The difference between explicit and reference-based copies is subtle, but can be really important.
# Try to keep in mind how a list is stored in the computer's memory.

[11.25, 18.0, 20.0, 10.75, 9.5]


<h1><center>Chapter 3: Functions and Packages</center></h1>

# Familiar functions

Out of the box, Python offers a bunch of built-in functions to make your life as a data scientist easier. You already know two such functions: print() and type(). You've also used the functions str(), int(), bool() and float() to switch between data types. These are built-in functions as well.

Calling a function is easy. To get the type of 3.0 and store the output as a new variable, result, you can use the following:

result = type(3.0) <br>

The general recipe for calling functions and saving the result to a variable is thus:

output = function_name(input)


**The len() function is extremely useful; it also works on strings to count the number of characters!**

In [24]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1

print(len(var1))
# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


# Help!

Maybe you already know the name of a Python function, but you still have to figure out how to use it. Ironically, you have to ask for information about a function with another function: help(). In IPython specifically, you can also use ? before the function name.

To get help on the max() function, for example, you can use one of these calls:

help(max) <br>
?max

# Multiple arguments

In the previous exercise, the square brackets around imag in the documentation showed us that the imag argument is optional. But Python also uses a different way to tell users about arguments being optional.

Have a look at the documentation of sorted() by typing help(sorted) in the IPython Shell.

You'll see that sorted() takes three arguments: iterable, key and reverse.

key=None means that if you don't specify the key argument, it will be None. reverse=False means that if you don't specify the reverse argument, it will be False.

In this exercise, you'll only have to specify iterable and reverse, not key. The first input you pass to sorted() will be matched to the iterable argument, but what about the second input? To tell Python you want to specify reverse without changing anything about key, you can use =:

sorted(-----, reverse = -----) <br>

Two lists have been created for you on the right. Can you paste them together and sort them in descending order?

Note: For now, we can understand an iterable as being any collection of objects, e.g. a List.

In [25]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted

full_sorted = sorted(full, reverse=True)
# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


# String Methods

Strings come with a bunch of methods. Follow the instructions closely to discover some of them. If you want to discover them in more detail, you can always type help(str) in the IPython Shell.

A string place has already been created for you to experiment with.

In [26]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up

place_up = place.upper()
# Print out place and place_up
print(place_up)
print(place)

# Print out the number of o's in place
print(place.count('o'))

POOLHOUSE
poolhouse
3


# List Methods

Strings are not the only Python types that have methods associated with them. Lists, floats, integers and booleans are also types that come packaged with a bunch of useful methods. In this exercise, you'll be experimenting with:

* index(), to get the index of the first element of a list that matches its input and
* count(), to get the number of times an element appears in a list.

You'll be working on the list with the area of different parts of a house: areas.

In [27]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
1


# List Methods (2)

Most list methods will change the list they're called on. Examples are:

* append(), that adds an element to the list it is called on,
* remove(), that removes the first element of a list that matches the input, and
* reverse(), that reverses the order of the elements in the list it is called on.

You'll be working on the list with the area of different parts of the house: areas.

In [28]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()
# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


# Import package

As a data scientist, some notions of geometry never hurt. Let's refresh some of the basics.

For a fancy clustering algorithm, you want to find the circumference, C
, and area, A
, of a circle. When the radius of the circle is r, you can calculate C
and A
 as:

C=2πr

A=πr2

To use the constant pi, you'll need the math package. A variable r is already coded in the script. Fill in the code to calculate C and A and see how the print() functions create some nice printouts.

In [29]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = math.pi*r*2

# Calculate A
A = math.pi*r*r

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


# Selective import

General imports, like import math, make all functionality from the math package available to you. However, if you decide to only use a specific part of a package, you can always make your import more selective:

from math import pi

Let's say the Moon's orbit around planet Earth is a perfect circle, with a radius r (in km) that is defined in the script.

In [30]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.

dist = r*radians(12)
# Print out dist
print(dist)

40317.10572106901


# Different ways of importing

There are several ways to import packages and modules into Python. Depending on the import call, you'll have to use different Python code.

Suppose you want to use the function inv(), which is in the linalg subpackage of the scipy package. You want to be able to use this function as follows:

my_inv([[1,2], [3,4]])

Which import statement will you need in order to run the above code without an error?

from scipy.linalg import inv as my_inv

<h1><center>Chapter 4: Numpy</center></h1>

# Your First NumPy Array

In this chapter, we're going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of numpy, a powerful package to do data science.

A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a numpy array from it?


In [31]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np

import numpy as np
# Create a numpy array from baseball: np_baseball
np_baseball = np.array([baseball])

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


# Baseball players' height

You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it and convert the units to meters?

height_in is already available and the numpy package is loaded, so you can start straight away (Source: stat.ucla.edu).

In [32]:
#Get current working directory
import os
os. getcwd()

# Reading the csv file 
import pandas as pd
from pandas import read_csv
filename = "/Users/anasbigmac/Desktop/DataCamp2020/Introduction to Python/baseball.csv"
df=read_csv(filename)
df.head(5)

Name Team       Position  Height  Weight    Age PosCategory
0    Adam_Donachie  BAL        Catcher      74     180  22.99     Catcher
1        Paul_Bako  BAL        Catcher      74     215  34.69     Catcher
2  Ramon_Hernandez  BAL        Catcher      72     210  30.78     Catcher
3     Kevin_Millar  BAL  First_Baseman      72     210  35.43   Infielder
4      Chris_Gomez  BAL  First_Baseman      73     188  35.71   Infielder

In [33]:
# Convert the height column to a list 
height_in = df['Height'].values.tolist()

In [34]:

# Import numpy
import numpy as np

# Create a numpy array from height: np_height_in
np_height_in = np.array(height_in)

# Print out np_height

print(np_height_in)
# Convert np_height to m: np_height_m
np_height_m = np_height_in* 0.0254

# Print np_height_m
print(np_height_m)

[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


In [35]:
# Convert the Weight column to a list 
weight_lb = df['Weight'].values.tolist()

In [36]:
# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi =  np_weight_kg / np_height_m ** 2

# Print out bmi
print(bmi)

[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


# Lightweight baseball players

To subset both regular Python lists and numpy arrays, you can use square brackets:

x = [4 , 9 , 6, 3, 1] <br>
x[1]

import numpy as np <br>
y = np.array(x) <br>
y[1]

For numpy specifically, you can also use boolean numpy arrays:

high = y > 5 <br>
y[high]

The code that calculates the BMI of all baseball players is already included. Follow the instructions and reveal interesting things from the data!

In [37]:
# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

print()

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

# It appears that only 11 of the more than 1000 baseball players have a BMI under 21!

[False False False ... False False False]

[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


# NumPy Side Effects

As Hugo explained before, numpy is great for doing vector arithmetic. If you compare its functionality with regular Python lists, however, some things have changed.

First of all, numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.

Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

Have a look at this line of code:

np.array([True, 1, 2]) + np.array([3, 4, False])

Can you tell which code chunk builds the exact same Python object? The numpy package is already imported as np, so you can start experimenting in the IPython Shell straight away!

np.array([4, 3, 0]) + np.array([0, 2, 2])

# Subsetting NumPy Arrays

You've seen it with your own eyes: Python lists and numpy arrays sometimes behave differently. Luckily, there are still certainties in this world. For example, subsetting (using the square bracket notation on lists or arrays) works exactly the same. To see this for yourself, try the following lines of code in the IPython Shell:

x = ["a", "b", "c"] <br>
x[1]

np_x = np.array(x) <br>
np_x[1]

The script on the right already contains code that imports numpy as np, and stores both the height and weight of the MLB players as numpy arrays.

In [38]:
# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

print()

# Print out sub-array of np_height: index 100 up to and including index 110
print(np_height_in[100:111])

200

[73 74 72 73 69 72 73 75 75 73 72]


# Your First 2D NumPy Array

Before working on the actual MLB data, let's try to create a 2D numpy array from a small list of lists.

In this exercise, baseball is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. baseball is already coded for you in the script.

In [39]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball

np_baseball = np.array(baseball)
# Print out the type of np_baseball

print(type(np_baseball))
# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


# Baseball data in 2D form

You have another look at the MLB data and realize that it makes more sense to restructure all this information in a 2D numpy array. This array should have 1015 rows, corresponding to the 1015 baseball players you have information on, and 2 columns (for height and weight).

The MLB was, again, very helpful and passed you the data in a different structure, a Python list of lists. In this list of lists, each sublist represents the height and weight of a single baseball player. The name of this embedded list is baseball.

Can you store the data as a 2D array to unlock numpy's extra functionality?

In [40]:
# Convert the height and weight column to a list 
baseball= df[['Height', 'Weight']].values.tolist()

In [41]:
# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(1015, 2)


# Subsetting 2D NumPy Arrays

If your 2D numpy array has a regular structure, i.e. each row and column has a fixed number of values, complicated ways of subsetting become very easy. Have a look at the code below where the elements "a" and "c" are extracted from a list of lists.

#regular list of lists <br>
x = [["a", "b"], ["c", "d"]] <br>
[x[0][0], x[1][0]] <br>

#numpy <br>
import numpy as np <br>
np_x = np.array(x) <br>
np_x[:,0]

For regular Python lists, this is a real pain. For 2D numpy arrays, however, it's pretty intuitive! The indexes before the comma refer to the rows, while those after the comma refer to the columns. The : is for slicing; in this example, it tells Python to include all rows.

The code that converts the pre-loaded baseball list to a 2D numpy array is already in the script. The first column contains the players' height in inches and the second column holds player weight, in pounds. Add some lines to make the correct selections. Remember that in Python, the first element is at index 0!

In [42]:
# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

print()

# Print out height of 124th player
print(np_baseball[123])

[ 70 195]

[ 75 200]


# 2D Arithmetic

Remember how you calculated the Body Mass Index for all baseball players? numpy was able to perform all calculations element-wise (i.e. element by element). For 2D numpy arrays this isn't any different! You can combine matrices with single numbers, with vectors, and with other matrices.

Execute the code below in the IPython shell and see if you understand:

import numpy as np <br>
np_mat = np.array([[1, 2], 
                   [3, 4], 
                   [5, 6]]) 

np_mat * 2 <br>
np_mat + np.array([10, 10]) <br>
np_mat + np_mat <br>

np_baseball is coded for you; it's again a 2D numpy array with 3 columns representing height (in inches), weight (in pounds) and age (in years).

In [43]:
# Convert the height, weight and age column to a numpy array 
updated= df[['Height', 'Weight', 'Age']].to_numpy()

# Convert the height and weight column to a list 
baseball= df[['Height', 'Weight','Age' ]].values.tolist()


In [44]:

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

print()

print()
# Create numpy array: conversion
conversion = 0.0254, 0.453592, 1

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[148.   360.    45.98]
 [148.   430.    69.38]
 [144.   420.    61.56]
 ...
 [150.   410.    50.38]
 [150.   380.    62.02]
 [146.   390.    55.84]]


[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]
 ...
 [ 1.905   92.98636 25.19   ]
 [ 1.905   86.18248 31.01   ]
 [ 1.8542  88.45044 27.92   ]]


# Average versus median

You now know how to use numpy functions to get a better feeling for your data. It basically comes down to importing numpy and then calling several simple functions on the numpy arrays:

import numpy as np <br>
x = [1, 4, 8, 10, 12]  <br>
np.mean(x)  <br>
np.median(x)  <br>

The baseball data is available as a 2D numpy array with 3 columns (height, weight, age) and 1015 rows. The name of this numpy array is np_baseball. After restructuring the data, however, you notice that some height values are abnormally high. Follow the instructions and discover which summary statistic is best suited if you're dealing with so-called outliers.

In [45]:

# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

73.6896551724138
74.0


# Explore the baseball data

Because the mean and median are so far apart, you decide to complain to the MLB. They find the error and send the corrected data over to you. It's again available as a 2D Numpy array np_baseball, with three columns.

The Python script on the right already includes code to print out informative messages with the different summary statistics. Can you finish the job?

In [46]:
# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 73.6896551724138
Median: 74.0
Standard Deviation: 2.312791881046546
Correlation: [[1.         0.53153932]
 [0.53153932 1.        ]]


# Blend it all together

In the last few exercises you've learned everything there is to know about heights and weights of baseball players. Now it's time to dive into another sport: soccer.

You've contacted FIFA for some data and they handed you two lists. The lists are the following:

positions = ['GK', 'M', 'A', 'D', ...] <br>
heights = [191, 184, 185, 180, ...] <br>

Each element in the lists corresponds to a player. The first list, positions, contains strings representing each player's position. The possible positions are: 'GK' (goalkeeper), 'M' (midfield), 'A' (attack) and 'D' (defense). The second list, heights, contains integers representing the height of the player in cm. The first player in the lists is a goalkeeper and is pretty tall (191 cm).

You're fairly confident that the median height of goalkeepers is higher than that of other players on the soccer field. Some of your friends don't believe you, so you are determined to show them using the data you received from FIFA and your newly acquired Python skills.

In [47]:
# Reading the fifa csv file 
df1 = pd.read_csv("/Users/anasbigmac/Desktop/DataCamp2020/Introduction to Python/fifa.csv",na_values="?")
df1

id                     name   rating  position   height    foot  \
0       1001             Gábor Király       69        GK      191   Right   
1     100143             Frederik Boi       65         M      184   Right   
2     100264          Tomasz Szewczuk       57         A      185   Right   
3     100325   Steeve Joseph-Reinette       63         D      180    Left   
4     100326             Kamel Chafni       72         M      181   Right   
...      ...                      ...      ...       ...      ...     ...   
8842    9801          Danijel Ljuboja       73         A      189    Left   
8843    9805            Craig Bellamy       79         A      175   Right   
8844    9807            Michel Breuer       68         D      183   Right   
8845    9815              Gill Swerts       65         D      179   Right   
8846    9913              Mehdi Nafti       69         M      179   Right   

       rare  pace  shooting  passing  dribbling  defending  heading  diving  \
0         0                                                              70   
1         0    61        65       63         59         62       62           
2         0    65        54       43         53         55       74           
3         0    68        38       51         46         64       71           
4         0    75        64       67         72         57       66           
...     ...   ...       ...      ...        ...        ...      ...     ...   
8842      1    62        73       64         74         56       68           
8843      0    80        78       67         81         62       71           
8844      0    61        40       56         51         70       74           
8845      0    65        48       63         65         67       69           
8846      0    55        56       64         65         69       60           

      handling  kicking  reflexes  speed   positioning  
0           66       63        74     35          66.0  
1                                                  NaN  
2                                                  NaN  
3                                                  NaN  
4                                                  NaN  
...        ...      ...       ...    ...           ...  
8842                                               NaN  
8843                                               NaN  
8844                                               NaN  
8845                                               NaN  
8846                                               NaN  

[8847 rows x 19 columns]

In [48]:
# Looking at the columns you can clearly see the space after the name etc. 
df1.columns

Index(['id', ' name', ' rating', ' position', ' height', ' foot', ' rare',
       ' pace', ' shooting', ' passing', ' dribbling', ' defending',
       ' heading', ' diving', ' handling', ' kicking', ' reflexes', ' speed',
       ' positioning'],
      dtype='object')

In [49]:
# I tried this to see the column names and I could see that that a space after id  
# but I didn't put two and two together 

for col in df1.columns:
    print(col)

id
 name
 rating
 position
 height
 foot
 rare
 pace
 shooting
 passing
 dribbling
 defending
 heading
 diving
 handling
 kicking
 reflexes
 speed
 positioning


In [51]:
# This is what I did to resolve the errors which were not by the naked eye because the code was right

#Re-put all the names back into the dataframe because it was throwing an error when I wanted to covert one column to a list 

#df1.columns=['id','name','rating','position','height',
   #          'foot','rare','pace','shooting','passing',
    #         'dribbling','defending','heading','diving',
     #        'handling','kicking','reflexes','speed','positioning']

#df1.info()


In [ ]:
# There are missing values but this is not a proper representation of those 
# Just tried it to see the dataframe
# df1.isnull().sum().sort_values(ascending=False)

In [ ]:
# This was where I was having a problem with the position and that space 
# Convert the position column to a list 
positions = df1[' position'].tolist()


In [ ]:
# Convert the height column to a list 
heights= df1[' height'].tolist()



In [ ]:
# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

np_positions 

In [ ]:
# Heights of the goalkeepers: gk_heights

gk_heights = np_heights[np_positions == ' GK']



In [ ]:
# Heights of the other players: other_heights
other_heights = np_heights[np_positions != ' GK']


# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

# Conclusion

I'm going to be brutally honest the fifa.csv file literally took me by surprise. I found it a positive challenge trying to figure out how to resolve the errors I was getting. I even turned to Facebook to ask in the python group i'm part of for some help. I did get some help but the issues I was experiencing weren't resovled. I then came up with a solution which worked. And other solutions were given to me by Asif Iqbal one of the members of the group. I also turned to my friends Aravind Subramaniam and Simranpal Kohil. Simranpal figured out my problem. It was so simple the error but I was not expecting nor looking for it. I was expecting the csv file to be cleaned because this is an introduction to python the course I undertook at Datacamp. But it just cause to show that one should always be prepared for the unexpected. It was a fun course and I learned alot. So I created this notebook as a reminder that yes Ana you did it. Like last year I was useless I couldn't understand what on earth I was getting myself into but now i'm getting more confidence as I keep progressing in this field. I hope whoever reads this might find it somewhat useful. 